### ISSUE TITLE
Hi, I am wondering how you connect your arduino to vga wire

### ISSUE THREAD

**Issue by roberthuang0306** [tttttx2/ddcvcp#1]

**Comment by tttttx2** [comment]
I used it with an ESP32, think it was the LOLIN/WEMOS D32 PRO board. For this purpose I threw together a quick and simple PCB over at https://oshwlab.com/tttttx2/esp32vga
It's not perfect (need to cut the top of the pin headers to fit and put some electrical tape to not short it out with the VGA connector but oh well)

Basically you need to connect GND, SDA and SCL of VGA (5,12,15 according to the pinout on the right side here https://en.wikipedia.org/wiki/VGA_connector) to the GND, SDA and SCL pins of your arduino. In my case those were 21/22 but  if I recall correctly, the library should work with whatever your board set as the default I2C pins for the Wire library.
Sometimes you also need to connect Pin9/KEY to 5V but probably not.

Keep in mind that my library here only provides control of the monitor settings (brightness, power on/off etc) and does not output any image. For this you'd better look up the one from Bitluni here https://github.com/bitluni/ESP32Lib

If you're interested, shoot me a DM over on twitter [https://twitter.com/tttttx2_](https://twitter.com/tttttx2_) with your shipping address and I'll send you one of my spare boards, but guess you have to assemble it yourself so it fits in a letter.
